/**
 * Grounded Output Types
 *
 * Every claim this system makes must be attributable to a specific data source.
 * These types enforce that structure across all engines.
 */

/** How confident we are in a claim, and why */
export type DataConfidence = "HIGH" | "MEDIUM" | "LOW" | "INSUFFICIENT"

/** Where a claim came from */
export type DataSource =
  | "STORED_FIELD"       // Directly stored in DB, no computation
  | "COMPUTED"           // Calculated from stored values (e.g., days since contact)
  | "RULE_BASED"         // Triggered by a deterministic rule (e.g., AUM > threshold)
  | "AI_DRAFT"           // Generated by AI — requires human review
  | "AI_DRAFT_FALLBACK"  // AI failed, this is a minimal template

/** A single fact claim with full provenance */
export interface GroundedClaim {
  value: string
  source: DataSource
  confidence: DataConfidence
  /** Specific field, record ID, or calculation that produced this value */
  evidence: string
}

/** A section of content with provenance */
export interface GroundedSection {
  title: string
  content: string | string[]
  source: DataSource
  confidence: DataConfidence
  evidenceRecords?: string[]  // IDs of records used
  missingData?: string[]      // What data would improve this
}

/** Top-level grounded output */
export interface GroundedOutput {
  generatedAt: string
  derivedFrom: string[]       // List of data sources consulted
  dataQuality: DataConfidence // Overall quality of inputs
  sections: GroundedSection[]
  missingData: string[]       // All missing data that would improve the output
  disclaimer?: string
}

/** A single scored signal with evidence */
export interface ScoredSignal {
  name: string
  triggered: boolean
  value?: number | string
  evidence: string
  source: DataSource
  confidence: DataConfidence
}

/** An opportunity grounded in real signals */
export interface GroundedOpportunity {
  id: string
  type: string
  title: string
  triggerRule: string         // Exact rule that triggered this
  triggerData: string         // The specific data values that matched
  evidence: string[]          // Specific record IDs and field names
  confidence: DataConfidence
  urgency: "HIGH" | "MEDIUM" | "LOW"
  suggestedAction: string
  missingData: string[]
}

/** A tax insight with explicit evidence */
export interface GroundedTaxInsight {
  triggerName: string
  triggerRule: string         // "If lifeStage === DISTRIBUTION"
  triggerData: string         // Actual field value that matched
  confidence: DataConfidence
  dataQuality: string         // "Based on stored lifeStage field only — no actual RMD calculation performed"
  estimatedImpact: string | null
  limitation: string          // "This is a draft observation, not a tax calculation"
}

export function formatAum(aum: number | null | undefined): string {
  if (!aum) return "Not on file"
  if (aum >= 1_000_000) return `$${(aum / 1_000_000).toFixed(1)}M`
  if (aum >= 1_000) return `$${(aum / 1_000).toFixed(0)}k`
  return `$${aum.toLocaleString()}`
}

export function daysSince(date: Date | null): number | null {
  if (!date) return null
  return Math.floor((Date.now() - new Date(date).getTime()) / 86_400_000)
}

export function confidenceLabel(c: DataConfidence): string {
  switch (c) {
    case "HIGH":         return "High — based on explicit stored data"
    case "MEDIUM":       return "Medium — derived from available signals"
    case "LOW":          return "Low — estimated from limited data"
    case "INSUFFICIENT": return "Insufficient data — analysis not possible"
  }
}
