import "server-only";

import PDFDocument from "pdfkit";
import { demoWalkthroughTracks, type DemoTrackId } from "@/lib/demo-walkthrough";
import { ensurePdfKitAssetFallbackInstalled } from "@/lib/pdfkit-runtime";

ensurePdfKitAssetFallbackInstalled();

export class DemoBriefExportService {
  static async generatePdf({
    organizationName,
    trackId,
    personaId,
    generatedBy,
  }: {
    organizationName: string;
    trackId: DemoTrackId;
    personaId: string;
    generatedBy: string;
  }): Promise<{ buffer: Buffer; fileName: string }> {
    const track = demoWalkthroughTracks[trackId];
    const persona = track.personas.find((candidate) => candidate.id === personaId) ?? track.personas[0];
    const generatedAt = new Date();

    const buffer = await new Promise<Buffer>((resolve, reject) => {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({
        size: "LETTER",
        margins: { top: 56, bottom: 56, left: 56, right: 56 },
        info: {
          Title: `${track.label} Demo Brief`,
          Author: organizationName,
          Subject: `Walkthrough brief for ${persona.label}`,
          Creator: "Drift AI Demo Brief",
        },
      });

      const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      doc.rect(0, 0, doc.page.width, 180).fill("#0f1720");
      doc.fillColor("#99f6e4").fontSize(11).text("CLIENT DEMO BRIEF", 56, 48, { width: pageWidth });
      doc.fillColor("#f8fafc").fontSize(28).text(`${track.label} Walkthrough`, 56, 68, { width: pageWidth });
      doc.fillColor("#cbd5e1").fontSize(12).text(track.description, 56, 108, { width: pageWidth, lineGap: 4 });
      doc.fillColor("#7dd3fc").fontSize(10).text(`Audience: ${track.audience}`, 56, 146, { width: pageWidth / 2 });
      doc.fillColor("#7dd3fc").fontSize(10).text(`Generated by ${generatedBy}`, 300, 146, { width: pageWidth / 2, align: "right" });

      doc.fillColor("#111827");
      doc.y = 210;

      doc.roundedRect(56, doc.y, pageWidth, 120, 16).fill("#ecfeff");
      doc.fillColor("#155e75").fontSize(11).text("ACTIVE PERSONA", 76, doc.y + 18);
      doc.fillColor("#0f172a").fontSize(22).text(persona.label, 76, doc.y + 38, { width: pageWidth - 40 });
      doc.fillColor("#334155").fontSize(11).text(persona.featuredClient, 76, doc.y + 68, { width: pageWidth - 40 });
      doc.fillColor("#475569").fontSize(10).text(persona.scenario, 76, doc.y + 86, { width: pageWidth - 40, lineGap: 3 });

      doc.y += 145;
      doc.fillColor("#0f172a").fontSize(15).text("Why this story works");
      doc.moveDown(0.4);
      doc.fillColor("#334155").fontSize(10).text(persona.whyItWins, { lineGap: 4 });

      doc.moveDown(1);
      doc.fillColor("#0f172a").fontSize(15).text("Proof points to mention");
      doc.moveDown(0.5);
      persona.proofPoints.forEach((point) => {
        doc.fillColor("#0f766e").fontSize(10).text("•", { continued: true });
        doc.fillColor("#334155").text(` ${point}`, { lineGap: 3 });
        doc.moveDown(0.2);
      });

      doc.moveDown(0.8);
      doc.fillColor("#0f172a").fontSize(15).text("Walkthrough sequence");
      doc.moveDown(0.6);

      track.steps.forEach((step, index) => {
        if (doc.y > 640) {
          doc.addPage();
        }

        doc.roundedRect(56, doc.y, pageWidth, 110, 12).fill(index % 2 === 0 ? "#f8fafc" : "#f1f5f9");
        doc.fillColor("#0891b2").fontSize(10).text(step.eyebrow, 74, doc.y + 14);
        doc.fillColor("#0f172a").fontSize(15).text(step.title, 74, doc.y + 30, { width: pageWidth - 36 });
        doc.fillColor("#475569").fontSize(10).text(step.summary, 74, doc.y + 52, { width: pageWidth - 36, lineGap: 3 });
        doc.fillColor("#0f766e").fontSize(9).text(`Presenter note: ${step.presenterNote}`, 74, doc.y + 82, {
          width: pageWidth - 36,
          lineGap: 2,
        });
        doc.y += 124;
      });

      doc.addPage();
      doc.fillColor("#0f172a").fontSize(16).text("Talking points by step");
      doc.moveDown(0.6);

      track.steps.forEach((step) => {
        if (doc.y > 660) {
          doc.addPage();
        }

        doc.fillColor("#0f172a").fontSize(13).text(step.title);
        doc.moveDown(0.2);
        step.talkingPoints.forEach((point) => {
          doc.fillColor("#0891b2").fontSize(10).text("•", { continued: true });
          doc.fillColor("#334155").text(` ${point}`, { lineGap: 3 });
          doc.moveDown(0.2);
        });
        doc.moveDown(0.7);
      });

      const footerY = doc.page.height - 36;
      doc.fontSize(8).fillColor("#94a3b8").text(
        `Generated ${generatedAt.toLocaleString("en-US")}  •  ${organizationName}  •  Internal demo prep`,
        56,
        footerY,
        { width: pageWidth, align: "center" },
      );

      doc.end();
    });

    const fileName = `demo_brief_${track.id}_${persona.id}_${generatedAt.toISOString().slice(0, 10)}.pdf`;
    return { buffer, fileName };
  }
}
