import "server-only";

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  Table,
  TableRow,
  TableCell,
  WidthType,
  ShadingType,
  Header,
  Footer,
  PageNumber,
  NumberFormat,
} from "docx";
import PDFDocument from "pdfkit";
import { AuditEventService } from "./audit-event.service";
import prisma from "@/lib/db";

/**
 * Document Export Service
 *
 * Generates compliance-ready DOCX and PDF documents for:
 * - Investment Policy Statements (IPS)
 * - New Client Proposals
 * - Billing Statements
 * - Audit Reports
 *
 * All documents include:
 * - Firm branding header
 * - Confidentiality notice footer
 * - Generation timestamp and version
 * - Data source attribution per section
 * - Compliance scan status
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface DocumentSection {
  title: string;
  content: string;
  dataSource: string;
  isAIGenerated: boolean;
  requiresReview: boolean;
}

interface DocumentInput {
  type: "IPS" | "PROPOSAL" | "BILLING_STATEMENT" | "AUDIT_REPORT";
  clientName: string;
  organizationName: string;
  sections: DocumentSection[];
  compliancePassed: boolean;
  complianceHits: number;
  version: number;
  generatedAt: Date;
  missingData: string[];
}

// ---------------------------------------------------------------------------
// DOCX Generation
// ---------------------------------------------------------------------------

export class DocumentExportService {
  /**
   * Generate a DOCX file buffer for the given document input.
   */
  static async generateDocx(input: DocumentInput): Promise<Buffer> {
    const doc = new Document({
      creator: input.organizationName,
      title: `${input.type} — ${input.clientName}`,
      description: `Generated by Drift AI on ${input.generatedAt.toISOString()}`,
      styles: {
        default: {
          document: {
            run: { font: "Calibri", size: 22 },
          },
          heading1: {
            run: { font: "Calibri", size: 32, bold: true, color: "1B3A5C" },
          },
          heading2: {
            run: { font: "Calibri", size: 26, bold: true, color: "2C5F8A" },
          },
        },
      },
      sections: [
        {
          properties: {
            page: {
              margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
            },
          },
          headers: {
            default: new Header({
              children: [
                new Paragraph({
                  alignment: AlignmentType.LEFT,
                  children: [
                    new TextRun({ text: input.organizationName, bold: true, size: 20, color: "1B3A5C" }),
                    new TextRun({ text: `  |  ${input.type}`, size: 20, color: "666666" }),
                    new TextRun({ text: `  |  ${input.clientName}`, size: 20, color: "666666" }),
                  ],
                }),
              ],
            }),
          },
          footers: {
            default: new Footer({
              children: [
                new Paragraph({
                  alignment: AlignmentType.CENTER,
                  children: [
                    new TextRun({ text: "CONFIDENTIAL — For Internal Use Only", italics: true, size: 16, color: "999999" }),
                    new TextRun({ text: `  |  Version ${input.version}  |  `, size: 16, color: "999999" }),
                    new TextRun({ text: `Page `, size: 16, color: "999999" }),
                    new TextRun({ children: [PageNumber.CURRENT], size: 16, color: "999999" }),
                  ],
                }),
              ],
            }),
          },
          children: [
            // Title page
            new Paragraph({ spacing: { after: 400 } }),
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({ text: input.type === "IPS" ? "Investment Policy Statement" : input.type === "PROPOSAL" ? "New Client Proposal" : input.type === "BILLING_STATEMENT" ? "Fee & Billing Statement" : "Audit Report", bold: true, size: 48, color: "1B3A5C" }),
              ],
            }),
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { before: 200 },
              children: [
                new TextRun({ text: `Prepared for ${input.clientName}`, size: 28, color: "333333" }),
              ],
            }),
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { before: 100 },
              children: [
                new TextRun({ text: `${input.organizationName}`, size: 24, color: "666666" }),
              ],
            }),
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { before: 100 },
              children: [
                new TextRun({ text: `Generated: ${input.generatedAt.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, size: 20, color: "999999" }),
                new TextRun({ text: `  |  Version ${input.version}`, size: 20, color: "999999" }),
              ],
            }),

            // Compliance status
            new Paragraph({ spacing: { before: 600 } }),
            new Paragraph({
              children: [
                new TextRun({ text: "Compliance Status: ", bold: true, size: 22 }),
                new TextRun({
                  text: input.compliancePassed ? "PASSED — No regulatory flags detected" : `${input.complianceHits} flag(s) detected — Review required`,
                  bold: true,
                  size: 22,
                  color: input.compliancePassed ? "228B22" : "CC0000",
                }),
              ],
            }),

            // Missing data warning
            ...(input.missingData.length > 0
              ? [
                  new Paragraph({ spacing: { before: 200 } }),
                  new Paragraph({
                    children: [
                      new TextRun({ text: "⚠ Data Gaps:", bold: true, size: 22, color: "CC8800" }),
                    ],
                  }),
                  ...input.missingData.map(
                    (m) =>
                      new Paragraph({
                        spacing: { before: 40 },
                        children: [new TextRun({ text: `  • ${m}`, size: 20, color: "996600" })],
                      }),
                  ),
                ]
              : []),

            // Page break before content
            new Paragraph({ spacing: { before: 400 } }),
            new Paragraph({
              children: [new TextRun({ text: "─".repeat(80), color: "CCCCCC", size: 16 })],
            }),

            // Document sections
            ...input.sections.flatMap((section) => [
              new Paragraph({
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 },
                children: [
                  new TextRun({ text: section.title }),
                  ...(section.requiresReview
                    ? [new TextRun({ text: "  [REQUIRES REVIEW]", bold: true, color: "CC8800", size: 20 })]
                    : []),
                ],
              }),
              ...section.content.split("\n").map(
                (line) =>
                  new Paragraph({
                    spacing: { after: 120 },
                    children: [
                      new TextRun({ text: line, size: 22 }),
                    ],
                  }),
              ),
              new Paragraph({
                spacing: { before: 100, after: 200 },
                children: [
                  new TextRun({ text: `Source: ${section.dataSource}`, italics: true, size: 16, color: "999999" }),
                  ...(section.isAIGenerated
                    ? [new TextRun({ text: "  |  AI-Assisted", italics: true, size: 16, color: "6B8FB5" })]
                    : []),
                ],
              }),
              new Paragraph({
                children: [new TextRun({ text: "─".repeat(80), color: "EEEEEE", size: 14 })],
              }),
            ]),

            // Disclaimer
            new Paragraph({ spacing: { before: 600 } }),
            new Paragraph({
              heading: HeadingLevel.HEADING_2,
              children: [new TextRun({ text: "Disclaimer" })],
            }),
            new Paragraph({
              spacing: { after: 80 },
              children: [
                new TextRun({
                  text: "This document was generated with AI assistance and is intended for review by a qualified financial advisor. All data points should be verified against source records before distribution. This document does not constitute financial advice and should not be relied upon as the sole basis for investment decisions.",
                  size: 18,
                  color: "666666",
                  italics: true,
                }),
              ],
            }),
          ],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    return Buffer.from(buffer);
  }

  /**
   * Generate a PDF file buffer for the given document input.
   */
  static async generatePdf(input: DocumentInput): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({
        size: "LETTER",
        margins: { top: 72, bottom: 72, left: 72, right: 72 },
        info: {
          Title: `${input.type} — ${input.clientName}`,
          Author: input.organizationName,
          Subject: `Generated by Drift AI on ${input.generatedAt.toISOString()}`,
          Creator: "Drift AI Document Engine",
        },
      });

      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Header
      doc.fontSize(10).fillColor("#1B3A5C")
        .text(input.organizationName, { align: "left" })
        .fontSize(8).fillColor("#999999")
        .text(`${input.type}  |  ${input.clientName}  |  Version ${input.version}`, { align: "right" });

      doc.moveDown(0.5);
      doc.strokeColor("#CCCCCC").lineWidth(0.5)
        .moveTo(72, doc.y).lineTo(540, doc.y).stroke();

      // Title
      doc.moveDown(2);
      doc.fontSize(24).fillColor("#1B3A5C")
        .text(input.type === "IPS" ? "Investment Policy Statement" : input.type === "PROPOSAL" ? "New Client Proposal" : input.type === "BILLING_STATEMENT" ? "Fee & Billing Statement" : "Audit Report", { align: "center" });

      doc.moveDown(0.5);
      doc.fontSize(14).fillColor("#333333")
        .text(`Prepared for ${input.clientName}`, { align: "center" });

      doc.moveDown(0.3);
      doc.fontSize(10).fillColor("#999999")
        .text(`${input.organizationName}`, { align: "center" });

      doc.moveDown(0.3);
      doc.fontSize(9).fillColor("#999999")
        .text(`Generated: ${input.generatedAt.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}  |  Version ${input.version}`, { align: "center" });

      // Compliance status
      doc.moveDown(1.5);
      doc.fontSize(10).fillColor("#333333")
        .text("Compliance Status: ", { continued: true })
        .fillColor(input.compliancePassed ? "#228B22" : "#CC0000")
        .text(input.compliancePassed ? "PASSED" : `${input.complianceHits} flag(s) — Review required`, { continued: false });

      // Missing data
      if (input.missingData.length > 0) {
        doc.moveDown(0.5);
        doc.fontSize(10).fillColor("#CC8800").text("Data Gaps:");
        input.missingData.forEach((m) => {
          doc.fontSize(9).fillColor("#996600").text(`  • ${m}`);
        });
      }

      // Divider
      doc.moveDown(1);
      doc.strokeColor("#CCCCCC").lineWidth(0.5)
        .moveTo(72, doc.y).lineTo(540, doc.y).stroke();

      // Sections
      for (const section of input.sections) {
        doc.moveDown(1);
        doc.fontSize(14).fillColor("#1B3A5C")
          .text(section.title + (section.requiresReview ? "  [REQUIRES REVIEW]" : ""));

        doc.moveDown(0.3);
        doc.fontSize(10).fillColor("#333333")
          .text(section.content, { lineGap: 3 });

        doc.moveDown(0.3);
        doc.fontSize(7).fillColor("#999999")
          .text(`Source: ${section.dataSource}${section.isAIGenerated ? "  |  AI-Assisted" : ""}`);

        doc.moveDown(0.5);
        doc.strokeColor("#EEEEEE").lineWidth(0.3)
          .moveTo(72, doc.y).lineTo(540, doc.y).stroke();
      }

      // Disclaimer
      doc.moveDown(2);
      doc.fontSize(12).fillColor("#2C5F8A").text("Disclaimer");
      doc.moveDown(0.3);
      doc.fontSize(8).fillColor("#666666")
        .text("This document was generated with AI assistance and is intended for review by a qualified financial advisor. All data points should be verified against source records before distribution. This document does not constitute financial advice and should not be relied upon as the sole basis for investment decisions.");

      // Footer
      const bottomY = doc.page.height - 50;
      doc.fontSize(7).fillColor("#999999")
        .text("CONFIDENTIAL — For Internal Use Only", 72, bottomY, { align: "center", width: 468 });

      doc.end();
    });
  }

  /**
   * Generate and persist a DOCX document, returning the document record ID.
   */
  static async generateAndStoreDocx(
    input: DocumentInput,
    clientId: string,
    organizationId: string,
    userId?: string,
  ): Promise<{ documentId: string; fileName: string; buffer: Buffer }> {
    const buffer = await this.generateDocx(input);
    const fileName = `${input.type}_${input.clientName.replace(/\s+/g, "_")}_v${input.version}_${new Date().toISOString().slice(0, 10)}.docx`;

    const doc = await prisma.document.create({
      data: {
        clientId,
        fileName,
        fileSize: buffer.length,
        documentType: input.type,
        status: "UPLOADED",
        summaryText: input.sections.map((s) => s.title).join(", "),
        keyPoints: input.sections.map((s) => ({ title: s.title, source: s.dataSource, aiGenerated: s.isAIGenerated, requiresReview: s.requiresReview })) as any,
        riskItems: { compliancePassed: input.compliancePassed, complianceHits: input.complianceHits, missingData: input.missingData, version: input.version } as any,
      },
    });

    await AuditEventService.appendEvent({
      organizationId,
      userId,
      action: "DOCUMENT_GENERATED",
      target: `Document:${doc.id}`,
      details: `Generated DOCX: ${fileName} (${buffer.length} bytes)`,
      severity: "INFO",
      metadata: { documentId: doc.id, format: "DOCX", type: input.type, clientName: input.clientName },
    });

    return { documentId: doc.id, fileName, buffer };
  }

  /**
   * Generate and persist a PDF document, returning the document record ID.
   */
  static async generateAndStorePdf(
    input: DocumentInput,
    clientId: string,
    organizationId: string,
    userId?: string,
  ): Promise<{ documentId: string; fileName: string; buffer: Buffer }> {
    const buffer = await this.generatePdf(input);
    const fileName = `${input.type}_${input.clientName.replace(/\s+/g, "_")}_v${input.version}_${new Date().toISOString().slice(0, 10)}.pdf`;

    const doc = await prisma.document.create({
      data: {
        clientId,
        fileName,
        fileSize: buffer.length,
        documentType: input.type,
        status: "UPLOADED",
        summaryText: input.sections.map((s) => s.title).join(", "),
        keyPoints: input.sections.map((s) => ({ title: s.title, source: s.dataSource, aiGenerated: s.isAIGenerated, requiresReview: s.requiresReview })) as any,
        riskItems: { compliancePassed: input.compliancePassed, complianceHits: input.complianceHits, missingData: input.missingData, version: input.version } as any,
      },
    });

    await AuditEventService.appendEvent({
      organizationId,
      userId,
      action: "DOCUMENT_GENERATED",
      target: `Document:${doc.id}`,
      details: `Generated PDF: ${fileName} (${buffer.length} bytes)`,
      severity: "INFO",
      metadata: { documentId: doc.id, format: "PDF", type: input.type, clientName: input.clientName },
    });

    return { documentId: doc.id, fileName, buffer };
  }
}
