import "server-only";

import PDFDocument from "pdfkit";
import { DashboardService } from "@/lib/services/dashboard.service";
import { ensurePdfKitAssetFallbackInstalled } from "@/lib/pdfkit-runtime";

ensurePdfKitAssetFallbackInstalled();

export class RoiReportExportService {
  static async generatePdf({
    organizationName,
    orgId,
    generatedBy,
  }: {
    organizationName: string;
    orgId: string;
    generatedBy: string;
  }): Promise<{ buffer: Buffer; fileName: string }> {
    // Get available dashboard data
    const summary = await DashboardService.getExecutiveSummary();

    const generatedAt = new Date();

    const buffer = await new Promise<Buffer>((resolve, reject) => {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({
        size: "LETTER",
        margins: { top: 56, bottom: 56, left: 56, right: 56 },
        info: {
          Title: `${organizationName} ROI Report`,
          Author: organizationName,
          Subject: "Firm ROI and operating proof report",
          Creator: "Drift AI ROI Report",
        },
      });

      const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Title
      doc.fillColor("#67e8f9").fontSize(11).text("FIRM ROI REPORT", 56, 48, { width: pageWidth });
      doc.fillColor("#f8fafc").fontSize(28).text(organizationName, 56, 68, { width: pageWidth });

      // Summary section
      if (summary) {
        doc.fillColor("#cbd5e1").fontSize(12).text(`Total AUM: ${summary.aum}`, 56, 120, { width: pageWidth });
        doc.fillColor("#cbd5e1").fontSize(12).text(`Active Clients: ${summary.activeClients}`, 56, 140, { width: pageWidth });
        doc.fillColor("#cbd5e1").fontSize(12).text(`Revenue Opportunities: ${summary.revenueOpportunities}`, 56, 160, { width: pageWidth });
      }

      // Footer
      doc.fillColor("#7dd3fc").fontSize(10).text(`Generated by ${generatedBy}`, 56, doc.page.height - 80, {
        width: pageWidth / 2,
      });
      doc.fillColor("#7dd3fc").fontSize(10).text(generatedAt.toLocaleString("en-US"), 300, doc.page.height - 80, {
        width: pageWidth / 2,
        align: "right",
      });

      doc.end();
    });

    const fileName = `${organizationName}-ROI-Report-${generatedAt.toISOString().split("T")[0]}.pdf`;

    return { buffer, fileName };
  }
}
