import "server-only";

import PDFDocument from "pdfkit";
import { DashboardService } from "@/lib/services/dashboard.service";
import { ensurePdfKitAssetFallbackInstalled } from "@/lib/pdfkit-runtime";

ensurePdfKitAssetFallbackInstalled();

export class RoiReportExportService {
  static async generatePdf({
    organizationName,
    orgId,
    generatedBy,
  }: {
    organizationName: string;
    orgId: string;
    generatedBy: string;
  }): Promise<{ buffer: Buffer; fileName: string }> {
    const [summary, valueProof, valueHistory] = await Promise.all([
      DashboardService.getExecutiveSummary(orgId),
      DashboardService.getValueProof(orgId),
      DashboardService.getValueHistory(orgId),
    ]);

    const generatedAt = new Date();

    const buffer = await new Promise<Buffer>((resolve, reject) => {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({
        size: "LETTER",
        margins: { top: 56, bottom: 56, left: 56, right: 56 },
        info: {
          Title: `${organizationName} ROI Report`,
          Author: organizationName,
          Subject: "Firm ROI and operating proof report",
          Creator: "Drift AI ROI Report",
        },
      });

      const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

      const ensureSpace = (height: number) => {
        if (doc.y + height > doc.page.height - 56) {
          doc.addPage();
        }
      };

      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      doc.rect(0, 0, doc.page.width, 188).fill("#08111a");
      doc.fillColor("#67e8f9").fontSize(11).text("FIRM ROI REPORT", 56, 48, { width: pageWidth });
      doc.fillColor("#f8fafc").fontSize(28).text(organizationName, 56, 68, { width: pageWidth });
      doc.fillColor("#cbd5e1").fontSize(12).text(valueHistory.narrative, 56, 108, { width: pageWidth, lineGap: 4 });
      doc.fillColor("#7dd3fc").fontSize(10).text(`Generated by ${generatedBy}`, 56, 156, { width: pageWidth / 2 });
      doc.fillColor("#7dd3fc").fontSize(10).text(generatedAt.toLocaleString("en-US"), 300, 156, {
        width: pageWidth / 2,
        align: "right",
      });

      doc.y = 220;
      doc.fillColor("#0f172a").fontSize(16).text("Executive snapshot");
      doc.moveDown(0.6);

      const snapshotCards = [
        { label: "Total AUM", value: summary.aum, detail: summary.aumChange },
        { label: "Active clients", value: summary.activeClients.toLocaleString(), detail: `${summary.prospects} prospects in pipeline` },
        { label: "Detected revenue", value: summary.revenueOpportunities, detail: `${summary.taxReviewPending ?? 0} tax reviews under active review` },
        { label: "Churn risk", value: summary.churnRisk.toLocaleString(), detail: `${summary.complianceFlags ?? 0} compliance flags open` },
      ];

      const cardX = 56;
      const cardY = doc.y;
      snapshotCards.forEach((card, index) => {
        const width = (pageWidth - 16) / 2;
        const x = cardX + (index % 2) * (width + 16);
        const y = cardY + Math.floor(index / 2) * 96;
        doc.roundedRect(x, y, width, 80, 14).fill(index % 2 === 0 ? "#ecfeff" : "#f8fafc");
        doc.fillColor("#155e75").fontSize(10).text(card.label.toUpperCase(), x + 16, y + 14, { width: width - 32 });
        doc.fillColor("#0f172a").fontSize(20).text(card.value, x + 16, y + 30, { width: width - 32 });
        doc.fillColor("#475569").fontSize(9).text(card.detail, x + 16, y + 56, { width: width - 32 });
      });

      doc.y = cardY + 208;
      ensureSpace(180);
      doc.fillColor("#0f172a").fontSize(16).text("Value proof");
      doc.moveDown(0.5);
      doc.fillColor("#334155").fontSize(10).text(valueProof.narrative, { width: pageWidth, lineGap: 4 });
      doc.moveDown(0.8);

      valueProof.cards.forEach((card) => {
        ensureSpace(72);
        doc.roundedRect(56, doc.y, pageWidth, 58, 12).fill("#f8fafc");
        doc.fillColor("#0f766e").fontSize(10).text(card.label.toUpperCase(), 72, doc.y + 12, { width: pageWidth - 32 });
        doc.fillColor("#0f172a").fontSize(18).text(card.value, 72, doc.y + 28, { width: 150 });
        doc.fillColor("#475569").fontSize(9).text(card.detail, 200, doc.y + 16, {
          width: pageWidth - 216,
          lineGap: 3,
        });
        doc.y += 70;
      });

      ensureSpace(170);
      doc.fillColor("#0f172a").fontSize(16).text("90-day operating proof");
      doc.moveDown(0.5);
      valueHistory.snapshots.forEach((snapshot) => {
        ensureSpace(68);
        doc.roundedRect(56, doc.y, pageWidth, 56, 12).fill("#eff6ff");
        doc.fillColor("#1d4ed8").fontSize(10).text(snapshot.label.toUpperCase(), 72, doc.y + 12, { width: pageWidth - 32 });
        doc.fillColor("#0f172a").fontSize(17).text(`${snapshot.value}  (${snapshot.delta})`, 72, doc.y + 28, {
          width: pageWidth - 32,
        });
        doc.fillColor("#475569").fontSize(9).text(snapshot.detail, 260, doc.y + 18, {
          width: pageWidth - 276,
          lineGap: 3,
        });
        doc.y += 66;
      });

      ensureSpace(180);
      doc.fillColor("#0f172a").fontSize(16).text("Weekly trend timeline");
      doc.moveDown(0.6);
      valueHistory.timeline.forEach((point) => {
        ensureSpace(28);
        doc.fillColor("#0891b2").fontSize(10).text(point.label, 56, doc.y, { width: 70 });
        doc.fillColor("#334155").fontSize(10).text(
          `Meetings ${point.meetings}   •   Pipeline $${point.pipelineK.toLocaleString()}k   •   Audit events ${point.auditEvents}`,
          128,
          doc.y,
          { width: pageWidth - 72 },
        );
        doc.y += 22;
      });

      ensureSpace(130);
      doc.moveDown(0.6);
      doc.roundedRect(56, doc.y, pageWidth, 84, 16).fill("#0f172a");
      doc.fillColor("#a7f3d0").fontSize(11).text("Budget conversation takeaway", 76, doc.y + 16, { width: pageWidth - 40 });
      doc.fillColor("#f8fafc").fontSize(12).text(valueHistory.proofNote, 76, doc.y + 34, {
        width: pageWidth - 40,
        lineGap: 4,
      });

      const footerY = doc.page.height - 36;
      doc.fontSize(8).fillColor("#94a3b8").text(
        `Generated ${generatedAt.toLocaleString("en-US")}  •  ${organizationName}  •  Internal operating proof`,
        56,
        footerY,
        { width: pageWidth, align: "center" },
      );

      doc.end();
    });

    const fileName = `roi_report_${organizationName.replace(/\s+/g, "_").toLowerCase()}_${generatedAt.toISOString().slice(0, 10)}.pdf`;
    return { buffer, fileName };
  }
}
